object Version {
  val scalaTest         = "3.2.19"
  val scalaCheck        = "1.18.0"
  val logback           = "1.5.7"
  val logbackContrib    = "0.1.5"
  val pekko             = "1.1.0-M1"
  val pekkoHttp         = "1.1.0-M1"
  val pekkoProjection   = "1.0.0"
  val pekkoKafka        = "1.1.0-M1"
  val slick             = "3.3.3"
  val scalikeJDBC       = "4.3.0"
  val scalikeJDBCStream = "4.3.0"
  val sslConfig         = "0.6.1"
  val postgres          = "42.7.3"
}
